import { describe, expect, it } from 'vitest';
import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { CreativeRenderer } from './renderer';
import type { TemplateDefinition } from './types';

dotenv.config({ path: '.env.local' });

describe('Live Template Render Test', () => {
  it('renders the follower confirmation template with real Instagram image', async () => {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    const { data: template, error } = await supabase
      .from('creative_templates')
      .select('*')
      .eq('id', 'b7e8d641-5a02-4f76-88c9-cf91b29a5a78')
      .single();

    expect(error).toBeNull();
    expect(template).toBeDefined();

    const context = {
      order: {
        code: 'PED-5000-TESTE',
        date: '19/09/2026',
        quantity: 5000,
        service: 'Seguidores Instagram',
        amount: 'R$ 49,90',
      },
      customer: {
        name: 'Cristiano',
        phone: '5511971121710',
      },
      instagram: {
        username: 'cristiano',
        profile_image: 'https://kzhvkfunvrhjvghhhart.supabase.co/storage/v1/object/public/chat-media/account-4fe971b8-cf70-45e2-8db3-c3eff700ae75/contacts/7cee47a8-3762-4a04-a23a-ef775cb18f26/instagram_avatar_48a1b3cfbd20409e.png',
      },
    };

    const result = await CreativeRenderer.render(
      template.definition as TemplateDefinition,
      context
    );

    expect(result.pngBuffer).toBeInstanceOf(Buffer);
    expect(result.pngBuffer.length).toBeGreaterThan(10000);
    expect(result.width).toBe(960);
    expect(result.height).toBe(960);
    console.log('LIVE RENDER SUCCESS! Generated bytes:', result.pngBuffer.length);
  }, 30000);

  it('renders flat context matching exact live webhook payload', async () => {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    const { data: template, error } = await supabase
      .from('creative_templates')
      .select('*')
      .eq('id', 'b7e8d641-5a02-4f76-88c9-cf91b29a5a78')
      .single();

    expect(error).toBeNull();

    const flatContext = {
      title: 'CONFIRMAÇÃO DE PEDIDO',
      name: 'Cristiano Ronaldo',
      code: 'PED-5000-CRISTIANO',
      instagram_username: 'cristiano',
      quantity: '5.000',
      service: 'Seguidores Instagram',
      date: '19/09/2026',
      profile_image: 'https://kzhvkfunvrhjvghhhart.supabase.co/storage/v1/object/public/chat-media/account-4fe971b8-cf70-45e2-8db3-c3eff700ae75/contacts/7cee47a8-3762-4a04-a23a-ef775cb18f26/instagram_avatar_48a1b3cfbd20409e.png',
      amount: 'R$ 49,90',
    };

    const result = await CreativeRenderer.render(
      template.definition as TemplateDefinition,
      flatContext
    );

    expect(result.svg).toContain('Cristiano Ronaldo');
    if (JSON.stringify(template.definition).includes('code')) {
      expect(result.svg).toContain('PED-5000-CRISTIANO');
    }
    expect(result.svg).toContain('@cristiano');
    expect(result.svg).toContain('5.000');
    expect(result.pngBuffer.length).toBeGreaterThan(15000);
    console.log('FLAT CONTEXT RENDER SUCCESS! Generated bytes:', result.pngBuffer.length);
  }, 30000);
});
